"""empty message

Revision ID: 253bc77bdd81
Revises: efa7e9d9276
Create Date: 2014-08-28 19:23:28.205000

"""

# revision identifiers, used by Alembic.
revision = '253bc77bdd81'
down_revision = 'efa7e9d9276'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy', sa.Column('academy_latlng', sa.String(length=255), nullable=True))
    op.drop_column('academy', 'latitude')
    op.drop_column('academy', 'longitude')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy', sa.Column('longitude', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('academy', sa.Column('latitude', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('academy', 'academy_latlng')
    ### end Alembic commands ###
