"""empty message

Revision ID: 52a4fef670d1
Revises: ae61cfbec8f
Create Date: 2014-08-21 22:27:12.187000

"""

# revision identifiers, used by Alembic.
revision = '52a4fef670d1'
down_revision = 'ae61cfbec8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academy_name', sa.String(length=255), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('academy_introduce', sa.Text(), nullable=True),
    sa.Column('teacher_introduce', sa.Text(), nullable=True),
    sa.Column('curriculum_introduce', sa.Text(), nullable=True),
    sa.Column('academy_address', sa.String(length=255), nullable=True),
    sa.Column('welcome_line', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('class_time', sa.Text(), nullable=True),
    sa.Column('class_fee', sa.String(length=255), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academy')
    ### end Alembic commands ###
