"""empty message

Revision ID: 8ff7a960b90
Revises: 253bc77bdd81
Create Date: 2014-08-28 19:52:13.454000

"""

# revision identifiers, used by Alembic.
revision = '8ff7a960b90'
down_revision = '253bc77bdd81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
