"""empty message

Revision ID: ae61cfbec8f
Revises: None
Create Date: 2014-08-21 20:56:05.957000

"""

# revision identifiers, used by Alembic.
revision = 'ae61cfbec8f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
