"""empty message

Revision ID: efa7e9d9276
Revises: 52a4fef670d1
Create Date: 2014-08-28 19:21:49.078000

"""

# revision identifiers, used by Alembic.
revision = 'efa7e9d9276'
down_revision = '52a4fef670d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academy', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('latitude', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('academy', sa.Column('longitude', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academy', 'longitude')
    op.drop_column('academy', 'location')
    op.drop_column('academy', 'latitude')
    op.drop_column('academy', 'category')
    ### end Alembic commands ###
